# JuliaFormatter configuration
# See https://domluna.github.io/JuliaFormatter.jl/stable/config/

style = "default"
indent = 4
margin = 100
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
short_to_long_function_def = false
always_use_return = false
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = false
