name = "MixedHierarchyGames"
uuid = "34713e38-c463-4aa7-98bb-85ffea4597e9"
version = "0.1.0"
authors = ["hmzh-khn", "jamesjingqili", "leedh0124"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
PATHSolver = "f5f7c340-0bb3-5c69-969a-41884d311d1b"
ParametricMCPs = "9b992ff8-05bb-4ea1-b9d2-5ef72d82f7ad"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
SymbolicTracingUtils = "77ddf47f-b2ab-4ded-95ee-54f4fa148129"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TrajectoryGamesBase = "ac1ac542-73eb-4349-ae1b-660ab3609574"

[compat]
BenchmarkTools = "1.6.0"
Graphs = "1.13.1"
InvertedIndices = "1.3.1"
LaTeXStrings = "1"
LinearSolve = "3.26.0"
PATHSolver = "1.7.8"
ParametricMCPs = "0.1.17"
Revise = "3.8.0"
SciMLBase = "2.87.0"
StatsPlots = "0.15.7"
SymbolicTracingUtils = "0.1.3"
Symbolics = "6.51.0"
TimerOutputs = "0.5.29"
TrajectoryGamesBase = "0.3.11"
