name = "MixedHierarchyGames"
uuid = "34713e38-c463-4aa7-98bb-85ffea4597e9"
authors = ["hmzh-khn", "jamesjingqili", "leedh0124"]
version = "0.1.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
ParametricMCPs = "9b992ff8-05bb-4ea1-b9d2-5ef72d82f7ad"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SymbolicTracingUtils = "77ddf47f-b2ab-4ded-95ee-54f4fa148129"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TrajectoryGamesBase = "ac1ac542-73eb-4349-ae1b-660ab3609574"

[compat]
Graphs = "1.13.1"
LinearSolve = "3.26.0"
ParametricMCPs = "0.1.17"
SciMLBase = "2.87.0"
SymbolicTracingUtils = "0.1.3"
Symbolics = "6.51.0"
TimerOutputs = "0.5.29"
TrajectoryGamesBase = "0.3.11"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
